remove bp from repo

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,2 +1,10 @@
 #!/bin/bash
-./bp run $@
+
+
+if ! [ -x "$(command -v bp)" ]; then
+    echo "Error: bp is not installed."
+    echo "See README on how to install it"
+    exit 1
+fi
+
+bp run $@
